name: 'DownloadSignedArtifact'
description: ''
inputs:
  SignedArtifactUrl:
    description: 'Signed artifact URL'
    required: true
    default: ${{ github.event.client_payload.artifactUrl }}
  AuthenticationToken:
    description: 'SignPath REST API access token. More detailes: https://about.signpath.io/documentation/build-system-integration#authorization'
    required: true
    default: ${{ github.event.client_payload.authenticationToken }}
  Target:
    description: 'Target path to download artifact'
    required: true
  ArtifactName:
    description: 'Name for the signed artifact, if empty the task will only download the file to the filesystem'
    required: false
    default: ${{ github.event.client_payload.artifactName + '-signed' }}
runs:
  using: 'node16'
  main: 'dist/index.js'