name: 'SubmitSigningRequest'
description: 'Submit the signing request to SignPath'
inputs:
  SignPathConnectorUrl:
    description: 'GitHub Actions SignPath connector URL'
    required: true
  SignPathApiUserToken:
    description: 'SignPath REST API access token. More detailes: https://about.signpath.io/documentation/build-system-integration#authorization'
    required: true
  OrganizationId:
    description: 'SignPath organization id. More detailes: https://about.signpath.io/documentation/getting-started'
    required: true
  ProjectSlug:
    description: 'SignPath project slug. More detailes: https://about.signpath.io/documentation/projects'
    required: true
  SigningPolicySlug:
    description: 'SignPath signing policy slug. More detailes: https://about.signpath.io/documentation/projects#signing-policies'
    required: true
  ArtifactConfigurationSlug:
    description: 'SignPath artifact configuration id. More detailes: https://about.signpath.io/documentation/projects#artifact-configurations'
    required: true

  ArtifactName:
    description: 'Name of the artifact to sign'
    required: true
  WorkflowRunId:
    description: 'Workflow run ID where the artifact requiring a signature was generated'
    required: true
    default: ${{ github.event.workflow_run.id }}
  DownloadArtifactWorkflowName:
    description: 'Name of the workflow that contains task for downloading the signed artifact from SignPath'
    required: false
  ArtifactContext:
    description: 'Additional information that canbe be used in the download signed artifact workflow to identify the artifact creation context'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'