name: 'SubmitSigningRequest'
description: ''
inputs:
  SignPathConnectorUrl:
    description: 'GitHub Actions SignPath connector URL'
    required: true
  CIUserToken:
    description: 'SignPath REST API access token. More detailes: https://about.signpath.io/documentation/build-system-integration#authorization'
    required: true
  OrganizationId:
    description: 'SignPath organization id. More detailes: https://about.signpath.io/documentation/getting-started'
    required: true
  ProjectSlug:
    description: 'SignPath project slug. More detailes: https://about.signpath.io/documentation/projects'
    required: true
  SigningPolicySlug:
    description: 'SignPath signing policy slug. More detailes: https://about.signpath.io/documentation/projects#signing-policies'
    required: true
  ArtifactConfigurationSlug:
    description: 'SignPath artifact configuration id. More detailes: https://about.signpath.io/documentation/projects#artifact-configurations'
    required: true

  ArtifactName:
    description: 'Name of the artifact to sign'
    required: true
  GitHubToken:
    description: 'GitHub access token'
    default: ${{ secrets.GITHUB_TOKEN }}
  WorkflowId:
    description: 'Workflow ID where the artifact requiring a signature was generated'
    required: true
    default: ${{ github.event.workflow_run.workflow_id }}
  WorkflowRunId:
    description: 'Workflow run ID where the artifact requiring a signature was generated'
    required: true
    default: ${{ github.event.workflow_run.id }}
  Data:
    description: 'Data to be signed'
    required: true
    default: ${{ github.event.workflow_run }}

runs:
  using: 'node16'
  main: 'dist/index.js'