name: Build App

on:
  push:
  pull_request:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Log Version
      run: "echo \"Version 1\""

    - name: Create artifact file
      run: "echo \"Build: ${{ matrix.configuration }}. Created on: \" > script.ps1"
    - name: Append create date
      shell: pwsh
      run: "echo (Get-Date -Format 'yyyy-MM-dd HH:mm:ss') >> script.ps1"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with: 
        name: ${{ matrix.configuration }}-artifact
        path: "script.ps1"
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: "script.ps1"
        key: build-cache
    # - uses: GuillaumeFalourd/wait-sleep-action@v1
    #   with:
    #     time: '2m'
