name: Build App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Create artifact file
      run: "echo \"Build: ${{ matrix.configuration }}. Created on: \" > script.ps1"
    - name: Append create date
      run: "echo:| time >> script.ps1"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with: 
        name: ${{ matrix.configuration }}-artifact
        path: "script.ps1"
