name: Build App

on:
 issue_comment:
   
 # push:
 # pull_request:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest

    steps:
    - name: Log Version
      run: "echo \"Version 1\""

    - name: Create artifact file
      run: "echo \"Build: ${{ matrix.configuration }}. Created on: \" > script.ps1"
    - name: Append create date
      shell: pwsh
      run: "echo (Get-Date -Format 'yyyy-MM-dd HH:mm:ss') >> script.ps1"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with: 
        name: ${{ matrix.configuration }}-artifact
        path: "script.ps1"
    # - uses: GuillaumeFalourd/wait-sleep-action@v1
    #   with:
    #     time: '2m'
