name: Build App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest

    env:
      Solution_Name: TestApp/TestApp.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with: 
        name: artifact-name
        path: "TestApp/MyScanner.ps1"
