name: Build App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest

    env:
      Solution_Name: TestApp/TestApp.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: zip
      uses: vimtor/action-zip@v1
      with:
        files: "TestApp/TestApp/bin/Debug/net7.0"
        dest: result.zip
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v3
      with: 
        name: artifact-name
        path: "TestApp/TestApp/program.cs"
