name: My Workflow

on:
  workflow_call:
    inputs:
      myinput:
        required: true
        type: string

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Child Step
        run: echo "My input value is ${{ inputs.myinput }}"
