name: Download Artifact

on:
  workflow_dispatch:
    inputs:
      signingRequestData:
        description: 'SignPath signing request data used by DownloadSignedArtifact action to download the signed artifact'
        required: true
      artifactContext:
        description: 'Additional information that identifies the artifact creation context'
        required: false

jobs:

  download:
    runs-on: windows-latest
    steps:
     - name: Run DownloadSignedArtifact
       uses: volbobvol/githubactionsgettoknow/Tasks/DownloadSignedArtifact@main
       with:
         AuthenticationToken: ${{ secrets.CI_USER_TOKEN }}
         #Target: 'signed-artifact-file-name.zip'
         ArtifactName: 'SignedArtifact'

  deployment:
    runs-on: windows-latest
    needs: download
    environment: 
      name: ${{ github.event.inputs.artifactContext }}
    steps:
      - name: Deploy artifact
        run: "echo \"Deploy to ${{ vars.ENV_NAME }} \""
