name: Download Artifact

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:

  download:

    runs-on: windows-latest

    steps:
     - env:
          MESSAGE: ${{ github.event.client_payload.argument }}
        run: echo $MESSAGE