name: Download Artifact

on:
  workflow_dispatch:
    inputs:
      argument:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'

jobs:

  download:

    runs-on: windows-latest
    steps:
       - run: echo "${{ github.event.inputs.argument }}"