name: Download Artifact

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:

  download:

    runs-on: windows-latest
    env:
          MESSAGE: ${{ github.event.client_payload.argument }}
    steps:
       - run: echo $MESSAGE