name: Sign App

on:
  workflow_run:
    workflows: [Build App]
    types: [completed]
permissions:
  actions: read
  contents: write
jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest

    steps:
     - name: Run SubmitSigningRequest
       uses: volbobvol/githubactionsgettoknow/Tasks/SubmitSigningRequest@main
       with:
         SignPathconnectorUrl: 'http://ciconnector-new.westeurope.cloudapp.azure.com'
         CIUserToken: 'sdfdfas'
         OrganizationId: '2cde3088-c473-4ca4-9c40-f5045412c616'
         ProjectSlug: 'Azure_DevOps_Integration'
         SigningPolicySlug: 'SigningPolicy'
         ArtifactConfigurationSlug: 'testzip'
         ArtifactName: 'artifact-name'