name: Sign App

on:
 push:
 pull_request:

# enviornment Variables
env:
  OrgId: d3bcfc23-d90f-43c4-878d-c52b60c4980c

jobs:
  build:
    permissions:
      actions: read  # get run data
      contents: read  # do checkout

    runs-on: windows-latest

    steps:
    
    - name: checkout
      uses: actions/checkout@v3

    - name: Upload the artifcat file
      uses: actions/upload-artifact@v4
      with: 
        name: original-artifact
        path: "./files/hello-world.exe"
    
    - name: Run submit signing request for FQA ORG1
      id: "submit_sr"
      uses: SignPath/github-actions/actions/submit-signing-request@v0.2
      with:
        connector-url: ''
        api-token: "${{ secrets.SIGN_PATH_API_TOKEN }}"
        organization-id: ${{ env.OrgId }}
        project-slug: 'TestGha'
        signing-policy-slug: 'SP'
        artifact-configuration-slug: 'initial'
        github-artifact-name: original-artifact
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        wait-for-completion: true
        output-artifact-directory: 'org/content'

    - name: Upload the signed artifcat file
      uses: actions/upload-artifact@v4
      with: 
        name: signed-artifact
        path: "org/content"

    - name: Log submit-signing-request task output for Org1
      run: |
           echo "signing-request-id [${{steps.submit_sr.outputs.signing-request-id }}]"
           echo "signing-request-web-url [${{steps.submit_sr.outputs.signing-request-web-url }}]"
           echo "signpath-api-url [${{steps.submit_sr.outputs.signpath-api-url }}]"
           echo "signed-artifact-download-url [${{steps.submit_sr.outputs.signed-artifact-download-url }}]"
